name:                permutation-safe
version:             0.1.0.0
github:              "fraser-dunlop/permutation-safe"
license:             BSD3
author:              "Fraser Dunlop"
maintainer:          "frjd2@st-andrews.ac.uk"
copyright:           "2018 Fraser Dunlop"
category:            "Combinatorics"
synopsis:            "Safely construct and apply permutations"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/fraser-dunlop/permutation-safe#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

tests:
  permutation-safe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - permutation-safe
    - QuickCheck
    - hspec
